dataset: "rescuenet_resized"
dataset_scale:  713
crop_size: 713
batch_size: 4
ACCUMUL_SIZE: 32
crop_size_eval: 713, 950
batch_size_eval: 20
LR: 0.0001
LR_DECAY: 0.995
DECAY_EVERY_N_EPOCHS: 1
beta1: 0.9
beta2: 0.999
weight_decay: 0.001
factor: 0.5
patience: 5
notes: ""

